### ISSUE TITLE
overloaded method value / with alternatives

### ISSUE THREAD

**Issue by TingHui-Luo** [Panrong/st4ml#3]
您好，我今天尝试按照你们quick start的步骤编译打包程序，发现出现了问题
![image](https://github.com/Panrong/st4ml/assets/58798528/328c336c-30ef-4140-a5c3-68602dad2292)
最后定位到为instances 的 Trajectory的 avgSpeed的 length / duration  中 即除法发生了错误，在我注释掉这个函数之后编译成功了

**Comment by kaiqiboy** [comment]
Hi Jerry, thanks for your feedback. The issue is resolved now. :)

**Comment by TingHui-Luo** [comment]
Thank for your reply and resolve,good luck~
